export const LIST_API: string = 'https://opser.api.dgtle.com/v1/sale/index/0';
export const CONTENT_API: string = 'https://opser.api.dgtle.com/v1/sale/detail/';
export const BOT_NAME:string = 'spidey';
export const IMAGE_SAVE_PATH: string = "E:\\coding\\electron\\wechaty-electron\\dist\\assets\\images\\";
export const WECHATID:string = 'Krapnik';
export const IMAGE_SAVE_EXTNAME: string = ".png";
export const SCHEDULE_SPAN:string = "59 * * * * *";
export const SHOTSCREEN_SPAN:number = 5000;
export const KEYWORD:string[] = ['switch','iphone','ns','ps4','联想','华为','小米']; 